server:
  # Compression is by default disabled???? Need compression for backend?
  compression:
    enabled: true
  # Http 1.0 is default for some reason
  http2:
    enabled: true
  port: 8080
logging:
  level:
    org:
      springframework:
        security: TRACE